
name: Add "for test" Label

on:
  pull_request:
    types:
      - closed

permissions:
  pull-requests: read

jobs:
  add_label:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Get PR commits messages
        id: pr-commit
        uses: actions/github-script@v6
        with:
          script: |
            const { data: commits } = await github.rest.pulls.listCommits({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: ${{ github.event.number }}
            });
            const messages = commits.map(commit => commit.commit.message);
            console.log(messages.join("\n"));
            const regex = /#(\d+)/g;
            const issue_id_list = messages.join("\n").match(regex).map(match => match.replace("#", ""));
            console.log(issue_id_list);
            core.setOutput("issue_id_list", JSON.stringify(issue_id_list));
      - name: Add label to issues
        uses: actions/github-script@v6
        with:
          script: |
            const issue_id_list = JSON.parse('${{ steps.pr-commits.outputs.issue_id_list }}');
            for (const issue_id of issue_id_list) {
              github.rest.issues.removeLabel({
                issue_number: issue_id,
                owner: context.repo.owner,
                repo: context.repo.repo,
                name: ["backlog", "todo", "doing"]
              });
              github.rest.issues.addLabels({
                issue_number: $issue_id,
                owner: context.repo.owner, 
                repo: context.repo.repo,
                labels: ["for test"]
              });
            }
      - name: Close Issue
        uses: peter-evans/close-issue@v3
        with:
          issue-number: 1
          comment: Auto-closing issue
  close_issue:
    needs: [ add_label ]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        issue_id: ${{fromJson(needs.add_label.outputs.issue_id_list)}}
    steps:
      - name: Close Issue ${{ matrix.issue_id }}
        uses: peter-evans/close-issue@v3
        with:
          issue-number: ${{ matrix.issue_id }}
          comment: close after pr merged \#${{ github.event.number }}

